import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "End User License Agreement (EULA)",
};

export default function EulaPage() {
  return (
    <main className="min-h-screen bg-black/[0.96] text-neutral-100 relative overflow-hidden">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-6">End User License Agreement (EULA)</h1>

        <div className="space-y-6 text-neutral-200">
          <p className="text-sm text-neutral-400">Last Updated: January 6, 2026</p>
          <p className="text-sm text-neutral-400">Effective Date: January 6, 2026</p>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">IMPORTANT – READ CAREFULLY</h2>
            <p>
              This End User License Agreement (&quot;Agreement&quot; or &quot;EULA&quot;) is a legally binding contract between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and shiftbloom studio., operated by Fabian Zimber (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), governing your access to and use of the Open Hallucination Index software, platform, application programming interfaces (APIs), and related services (collectively, the &quot;Software&quot; or &quot;Service&quot;).
            </p>
            <p>
              BY ACCESSING, DOWNLOADING, INSTALLING, OR USING THE SOFTWARE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT ACCESS OR USE THE SOFTWARE.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">1. Definitions</h2>
            <p>
              <strong>&quot;Software&quot;</strong> means the Open Hallucination Index web application, APIs, documentation, and any updates, modifications, or enhancements thereto provided by the Company.
            </p>
            <p>
              <strong>&quot;OHI Tokens&quot;</strong> means the digital usage credits purchased by the User to access certain features and functionalities of the Software.
            </p>
            <p>
              <strong>&quot;User Content&quot;</strong> means any text, data, information, or other materials submitted, uploaded, or otherwise provided by the User through the Software.
            </p>
            <p>
              <strong>&quot;Output&quot;</strong> means any analysis results, verification scores, reports, or other information generated by the Software based on User Content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">2. Grant of License</h2>
            <p>
              <strong>2.1 License Grant.</strong> Subject to the terms and conditions of this Agreement, the Company grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Software solely for your personal or internal business purposes.
            </p>
            <p>
              <strong>2.2 Scope of License.</strong> This license does not include any right to:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Modify, adapt, translate, reverse engineer, decompile, disassemble, or create derivative works based on the Software, except as expressly permitted by applicable law;</li>
              <li>Copy, distribute, publicly display, or publicly perform the Software or any portion thereof;</li>
              <li>Rent, lease, lend, sell, sublicense, assign, or otherwise transfer rights to the Software;</li>
              <li>Remove, alter, or obscure any proprietary notices, labels, or marks on the Software;</li>
              <li>Use the Software for any purpose that is unlawful or prohibited by this Agreement.</li>
            </ul>
            <p>
              <strong>2.3 Reservation of Rights.</strong> The Company reserves all rights not expressly granted to you in this Agreement. The Software is licensed, not sold.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">3. User Account and Registration</h2>
            <p>
              <strong>3.1 Account Creation.</strong> To access certain features of the Software, you must create a user account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete.
            </p>
            <p>
              <strong>3.2 Account Security.</strong> You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
            </p>
            <p>
              <strong>3.3 Account Termination.</strong> We reserve the right to suspend or terminate your account at any time, with or without cause, and with or without notice, including for violation of this Agreement.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">4. OHI Tokens</h2>
            <p>
              <strong>4.1 Nature of Tokens.</strong> OHI Tokens are digital usage credits that enable access to specific features of the Software. OHI Tokens have no monetary value outside the Software, are not legal tender, and are not cryptocurrency or any form of investment.
            </p>
            <p>
              <strong>4.2 Purchase and Use.</strong> OHI Tokens may be purchased through the Software. Tokens are non-refundable except as expressly provided in this Agreement or required by applicable law. Tokens are consumed upon use of applicable Software features.
            </p>
            <p>
              <strong>4.3 No Expiration (Current Policy).</strong> Currently, OHI Tokens do not expire. However, we reserve the right to modify this policy with reasonable advance notice. Any such changes will apply only to tokens purchased after the effective date of the policy change.
            </p>
            <p>
              <strong>4.4 Non-Transferability.</strong> OHI Tokens are tied to your user account and may not be transferred, sold, traded, or exchanged to or with any third party.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">5. User Content and Conduct</h2>
            <p>
              <strong>5.1 User Responsibility.</strong> You are solely responsible for all User Content you submit to the Software. You represent and warrant that you have all necessary rights to submit such content and that your use of the Software does not violate any applicable law or third-party rights.
            </p>
            <p>
              <strong>5.2 Prohibited Uses.</strong> You agree not to use the Software to:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Upload, transmit, or distribute any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable;</li>
              <li>Violate any applicable local, state, national, or international law or regulation;</li>
              <li>Infringe upon or violate the intellectual property rights or privacy rights of any third party;</li>
              <li>Attempt to gain unauthorized access to the Software, other user accounts, or computer systems or networks;</li>
              <li>Interfere with or disrupt the integrity or performance of the Software;</li>
              <li>Engage in automated data collection (scraping, crawling) without express written consent;</li>
              <li>Use the Software for competitive analysis or to develop a competing product or service;</li>
              <li>Circumvent, disable, or otherwise interfere with security-related features of the Software.</li>
            </ul>
            <p>
              <strong>5.3 License to User Content.</strong> By submitting User Content, you grant the Company a non-exclusive, worldwide, royalty-free license to use, process, store, and analyze such content solely for the purpose of providing and improving the Software. We do not claim ownership of your User Content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">6. Intellectual Property Rights</h2>
            <p>
              <strong>6.1 Company Property.</strong> The Software, including all intellectual property rights therein (such as copyrights, patents, trademarks, trade secrets, and other proprietary rights), is and shall remain the exclusive property of the Company and its licensors.
            </p>
            <p>
              <strong>6.2 Feedback.</strong> If you provide any suggestions, ideas, enhancement requests, feedback, or other recommendations regarding the Software (&quot;Feedback&quot;), you hereby assign to the Company all right, title, and interest in and to such Feedback, and the Company shall be free to use the Feedback without any attribution or compensation to you.
            </p>
            <p>
              <strong>6.3 Output Ownership.</strong> Subject to your compliance with this Agreement, you retain ownership of any original creative content you create using the Output. However, the methods, algorithms, and processes used to generate the Output remain our proprietary intellectual property.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">7. Privacy and Data Protection</h2>
            <p>
              <strong>7.1 Privacy Policy.</strong> Your use of the Software is subject to our Privacy Policy, which is incorporated into this Agreement by reference. Please review the Privacy Policy to understand our data collection and processing practices.
            </p>
            <p>
              <strong>7.2 GDPR Compliance.</strong> If you are located in the European Economic Area (EEA), we process your personal data in accordance with the General Data Protection Regulation (GDPR). You have certain rights under the GDPR, as detailed in our Privacy Policy.
            </p>
            <p>
              <strong>7.3 Data Security.</strong> We implement appropriate technical and organizational measures to protect your personal data. However, no method of transmission over the Internet or electronic storage is completely secure, and we cannot guarantee absolute security.
            </p>
            <p>
              <strong>7.4 Analytics.</strong> With your consent, we use Vercel Analytics to collect anonymous, aggregated data about how you use the Software. This helps us improve our services. You can manage your analytics preferences through our cookie consent banner. For more information, see our Privacy Policy and Cookie Policy.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">8. Disclaimers and Limitations</h2>
            <p>
              <strong>8.1 &quot;AS IS&quot; Provision.</strong> THE SOFTWARE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>
            <p>
              <strong>8.2 No Guarantee of Accuracy.</strong> THE COMPANY DOES NOT WARRANT THAT THE OUTPUT OR ANY ANALYSIS PROVIDED BY THE SOFTWARE WILL BE ACCURATE, COMPLETE, RELIABLE, OR ERROR-FREE. THE SOFTWARE IS INTENDED AS A TOOL TO ASSIST USERS AND SHOULD NOT BE RELIED UPON AS THE SOLE BASIS FOR ANY DECISION.
            </p>
            <p>
              <strong>8.3 Availability.</strong> We do not guarantee that the Software will be available at all times or that access will be uninterrupted or error-free. We may modify, suspend, or discontinue the Software at any time without liability.
            </p>
            <p>
              <strong>8.4 Third-Party Services.</strong> The Software may integrate with or contain links to third-party services. We are not responsible for the content, policies, or practices of any third-party services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">9. Limitation of Liability</h2>
            <p>
              <strong>9.1 Exclusion of Damages.</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Your access to or use of or inability to access or use the Software;</li>
              <li>Any conduct or content of any third party on the Software;</li>
              <li>Any content obtained from the Software;</li>
              <li>Unauthorized access, use, or alteration of your transmissions or content.</li>
            </ul>
            <p>
              <strong>9.2 Liability Cap.</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE TOTAL LIABILITY OF THE COMPANY FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT OR THE SOFTWARE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO THE COMPANY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED EUROS (€100).
            </p>
            <p>
              <strong>9.3 Exceptions.</strong> Nothing in this Agreement shall exclude or limit liability for (a) death or personal injury caused by negligence, (b) fraud or fraudulent misrepresentation, or (c) any other liability that cannot be excluded or limited under applicable law.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">10. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless the Company and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs, or expenses (including reasonable attorneys&apos; fees) arising from:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Your use of the Software;</li>
              <li>Your violation of this Agreement;</li>
              <li>Your violation of any third-party rights, including intellectual property or privacy rights;</li>
              <li>Any User Content you submit through the Software.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">11. Term and Termination</h2>
            <p>
              <strong>11.1 Term.</strong> This Agreement is effective upon your first access to or use of the Software and continues until terminated.
            </p>
            <p>
              <strong>11.2 Termination by You.</strong> You may terminate this Agreement at any time by discontinuing use of the Software and, if applicable, deleting your user account.
            </p>
            <p>
              <strong>11.3 Termination by Company.</strong> We may terminate or suspend your access to the Software immediately, without prior notice or liability, for any reason, including breach of this Agreement.
            </p>
            <p>
              <strong>11.4 Effects of Termination.</strong> Upon termination: (a) all rights and licenses granted to you under this Agreement will immediately cease; (b) you must immediately cease all use of the Software; (c) any unused OHI Tokens may be forfeited unless otherwise required by applicable law; (d) the Company may delete your account and User Content.
            </p>
            <p>
              <strong>11.5 Survival.</strong> Sections 6 (Intellectual Property), 8 (Disclaimers), 9 (Limitation of Liability), 10 (Indemnification), and 13 (Governing Law) shall survive termination of this Agreement.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">12. Modifications to Agreement</h2>
            <p>
              <strong>12.1 Right to Modify.</strong> We reserve the right to modify this Agreement at any time. We will provide notice of material changes by posting the updated Agreement on the Software or by other reasonable means.
            </p>
            <p>
              <strong>12.2 Acceptance of Changes.</strong> Your continued use of the Software after the effective date of any modifications constitutes your acceptance of the modified Agreement. If you do not agree to the modified terms, you must discontinue use of the Software.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">13. Governing Law and Dispute Resolution</h2>
            <p>
              <strong>13.1 Governing Law.</strong> This Agreement shall be governed by and construed in accordance with the laws of the Federal Republic of Germany, excluding its conflict of law provisions and the United Nations Convention on Contracts for the International Sale of Goods (CISG).
            </p>
            <p>
              <strong>13.2 Consumer Rights.</strong> If you are a consumer residing in the European Union, you may also benefit from mandatory provisions of the consumer protection laws of your country of residence. Nothing in this Agreement affects your rights as a consumer to rely on such mandatory provisions.
            </p>
            <p>
              <strong>13.3 Jurisdiction.</strong> For non-consumer disputes, the courts of Hamburg, Germany shall have exclusive jurisdiction. For consumer disputes, you may bring proceedings in the courts of your country of residence or the courts of Germany.
            </p>
            <p>
              <strong>13.4 Online Dispute Resolution.</strong> The European Commission provides a platform for online dispute resolution (ODR) at{" "}
              <a href="https://ec.europa.eu/consumers/odr/" className="text-blue-400 hover:underline">
                https://ec.europa.eu/consumers/odr/
              </a>
              . We are not obligated and currently not willing to participate in dispute resolution proceedings before a consumer arbitration board.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">14. General Provisions</h2>
            <p>
              <strong>14.1 Entire Agreement.</strong> This Agreement, together with the Privacy Policy and any other legal notices or policies published by us, constitutes the entire agreement between you and the Company regarding the Software and supersedes all prior agreements and understandings.
            </p>
            <p>
              <strong>14.2 Severability.</strong> If any provision of this Agreement is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.
            </p>
            <p>
              <strong>14.3 Waiver.</strong> No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term. Our failure to enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision.
            </p>
            <p>
              <strong>14.4 Assignment.</strong> You may not assign or transfer this Agreement or your rights hereunder without our prior written consent. We may freely assign this Agreement without restriction.
            </p>
            <p>
              <strong>14.5 Force Majeure.</strong> We shall not be liable for any failure or delay in performance resulting from circumstances beyond our reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, strikes, or government actions.
            </p>
            <p>
              <strong>14.6 Notices.</strong> All notices to the Company should be sent to: hi@shiftbloom.studio. Notices to you will be sent to the email address associated with your account.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-neutral-100">15. Contact Information</h2>
            <p>
              If you have any questions about this Agreement, please contact us at:
            </p>
            <p>
              shiftbloom studio.<br />
              Fabian Zimber<br />
              Up de Worth 6a<br />
              22927 Großhansdorf<br />
              Germany<br />
              Email: hi@shiftbloom.studio
            </p>
          </section>

          <hr className="border-white/10 my-8" />

          <section className="space-y-3 bg-slate-900/50 p-6 rounded-lg border border-slate-700">
            <h2 className="text-xl font-semibold text-neutral-100">Acknowledgment</h2>
            <p>
              BY USING THE SOFTWARE, YOU ACKNOWLEDGE THAT YOU HAVE READ THIS AGREEMENT, UNDERSTAND IT, AND AGREE TO BE BOUND BY ITS TERMS AND CONDITIONS.
            </p>
          </section>

          <hr className="border-white/10 my-8" />
          <p className="text-xs text-neutral-500">
            Note: This EULA was created as a template/draft and does not replace individual legal advice. Please review with qualified legal counsel to ensure compliance with applicable laws and alignment with your specific business practices.
          </p>
        </div>
      </div>
    </main>
  );
}
